<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodebaseAssistant.Domain\CodebaseAssistant.Domain.csproj" />
    <ProjectReference Include="..\CodebaseAssistant.Shared\CodebaseAssistant.Shared.csproj" />
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="Mappings\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="11.0.0" />
  </ItemGroup>

</Project>
